### ISSUE TITLE
Issues #49, #292, and #431 were closed, but problem is ongoing.

### ISSUE THREAD

**Issue by gannon345** [reicast/reicast-emulator#1010]
Supposedly the issue was resolved as of build ccfb6b6, but I've confirmed the problem still exists on multiple games, even as of the latest build. Thought I'd open a new issue, as I'm not sure if closed issues are still being looked at.

Screenshot here: https://cloud.githubusercontent.com/assets/8151956/23689131/deda79ac-0375-11e7-9166-30d82647161f.png

**Comment by Zetchzie** [comment]
I think reicast is... dying. id go to redream or Demul

**Comment by gannon345** [comment]
That's gonna be difficult to do on an Android device. Reicast is currently the only portable option I know of.

**Comment by uhbandduhn** [comment]
I think those who don't contribute in code don't get to troll in other
languages.

**Comment by Zetchzie** [comment]
Not trying to troll -_- but I haven't seen reicast updated since Dec 31 2016. Im a bit worried about dev.

**Comment by gannon345** [comment]
Three months is hardly the longest Reicast has gone without an update. Developers do have lives, and sometimes projects don't get updated for a while. I'll refrain from judgment unless the devs specify the project is dead.

**Comment by gannon345** [comment]
If it helps, I tested a ton of builds, and found that 1a79ce3 (2015-03-05T14:00:16.000Z) is working as expected in terms of the graphics on Fire Pro Wrestling D. Haven't tested other games yet, but will be doing so tonight or tomorrow when I have the time. Might be worth comparing 1a79ce3 with current builds to see what's different.

**Comment by gannon345** [comment]
Confirmed Street Fighter 3 is still buggy on 1a79ce3. It only fixed Fire Pro Wrestling D, so maybe the SF3/MvsC issues are a separate problem from what was happening on FPWD, and just looked like a similar problem.

I am still happy to be able to play my game, and hopefully this info is helpful toward fixing issues.

**Comment by ijoinit** [comment]
And the iOS version  just stillborn,I might never see that in my life.

**Comment by LoungeKatt** [comment]
@Zetchzie and the deleted user:

You are trying to run an emulator of one system on a different system. Not EVERY game is going to be perfect or easily supported. Dolphin only runs on select hardware, Play barely runs at all, but reicast has a few games with issues. It seems like that is fairly decent in terms of portable emulation. NES runs great, but how long has the original Nintendo been around, let alone discontinued.

The IOS version is not stillborn. Apple charges $100 / year for developer distribution tools. You are still able to download and run them locally for free, but they continue to make efforts that they are not used for any sort of commercial product without being a paid member. A jailbreak will allow you to run the code, but compiling it for distribution is tedious. You cannot blame a repository for being dead because it is not providing you with the finished product. It provides the code. That is its purpose.

@gannon345 
It could also be related to Android 7. There were a lot of graphics changes in that version of Android that may have interfered with the fixes to reicast. Is that still the version you are using to test? Have you tried with an older version using the same game? I don't have the game handy, so I cannot verify against older Android at the moment.

**Comment by rrrh** [comment]
@gannon345, can i close this issue (is it still a issue?) just to clean up a bit and settle the fog/smoke?

**Comment by skmp** [comment]
Yeah, has the information been transcribed to appropriate tickets?

**Comment by skmp** [comment]
Closing this in favor of per game tickets.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#92
