### ISSUE TITLE
Physical controller triggers cant be mapped

### ISSUE THREAD

**Issue by pishcakes** [reicast/reicast-emulator#1014]
Using shoulder buttons for crazy taxi isn't ideal lol

**Comment by pishcakes** [comment]
Using amazon fire tv

**Comment by LoungeKatt** [comment]
The issue with mapping triggers is that they are completely different than buttons. The buttons are strictly click, while triggers have motion so that the magnitude of a press is registered. It is possible to map a trigger, but it would require registering a set amount of pressure to emulate a button. The issue is that it becomes a bit unreliable by doing this.
