### ISSUE TITLE
Bios time keeps reseting 

### ISSUE THREAD

**Issue by flexoduss** [reicast/reicast-emulator#1061]
First of all thanks a lot for putting so much effort in this emulator. It brings back a lot of good memories. But I'm facing a small problem right now. I'm running retroarch on debian. And i tried all kinds of different bios files, but the bios time keeps reseting. Is there any fix for this problem?

**Comment by ParmuSingh** [comment]
1) open bios
2) set date and time
3) close bios
4) restart app and check. It should no longer ask you for date.

**Comment by sabula310** [comment]
hello  i notice that most device that are 5.1.1 dont work with reicast ,
will this be fix in the future or the next build verison

**Comment by flexoduss** [comment]
@ParmuSingh thank you :)

**Comment by sabula310** [comment]
On Nov 26, 2017 4:20 PM, "flexoduss" <notifications@github.com> wrote:

@ParmuSingh <https://github.com/parmusingh> thank you :)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/reicast/reicast-emulator/issues/1061#issuecomment-347051127>,
or mute the thread

**Comment by AbandonedCart** [comment]
This has finally been resolved across platforms.
