### ISSUE TITLE
reicast removes spaces in file names before reading files.

### ISSUE THREAD

**Issue by crocket** [reicast/reicast-emulator#1084]
Git Commit : `b4631f6715ab7ee8483ebcef37a97f6e3194602e`
OS : Gentoo Linux

When I try to run `gdi` files whose file names have spaces, I see the following message.

```
$ reicast /path/to/Dead\ or\ Alive\ 2\ \(USA\).gdi
......
......
GDI : 3 tracks
file[1] "DeadorAlive2(USA)(Track1).bin": FAD:0, CTRL:4, SSIZE:2352, OFFSET:0
Verify Failed  : file!=0
 in RawTrackFile -> ../../core/imgread/common.h : 273
```

reicast fails because it removes spaces in file names before opening the files.
reicast should not remove spaces in file names.

**Comment by chataigne73** [comment]
I saw this problem was fixed in libretro reicast core
can it be fixed her too ?
thx

**Comment by LoungeKatt** [comment]
Wouldn't it be awesome if they actually passed changes like that back to the origin repository and didn't just package it as part of their product and walk away?

**Comment by i30817** [comment]
The commit isn't supposed to fix this spaces bug and i already committed here anyway.

**Comment by LoungeKatt** [comment]
That wasn't directed at you. It was more a statement about how there is a whole separate program that has a lot of beneficial input for the core as a whole, but keeps it as a separate project.

**Comment by i30817** [comment]
I think it's pretty obvious nothing will happen because reicast is 

1. not a core on RA that has many coders working on it. In fact the only change i can see that isn't 'fix makefile' is from about 9 months ago.
2. RA doesn't require a Licensing agreement and has no intention of doing so, so even if they tried to push commits they'd still be contributing to someone attempt to sell that code after, which they probably don't want considering the history of parasites trying to take RA cores and selling them.

**Comment by LoungeKatt** [comment]
CLAs are a product of the modern era of liability. Everyone wants see a program work, but nobody is willing to take responsibility when it breaks. People submit a change and then want compensation. A third-party project forks the code, makes a ton of edits, but then refers people to the original source when there are questions. All of these things are easier to address when the source has one clear "owner" despite there being obvious paper trails of who authored it.

**Comment by LoungeKatt** [comment]
Fixed in https://github.com/reicast/reicast-emulator/commit/fb418d568ce6fb4f52d25a784b7d89bf57d5fbe5
