### ISSUE TITLE
Missing Touch Controller in KOF The Evolution after Dreamcast Intro

### ISSUE THREAD

**Issue by Emulatorer** [reicast/reicast-emulator#1143]
Im Using reicast r8 someone give me the link of this emulator I tried to play KOF The Evolution but after the intro of Dreamcast the touch controller is gone?

Note: If this issue is already reported I will close this emedietly

Android 5.1
Mali-450

**Comment by Jinzombie** [comment]
![screenshot_2018-04-29-13-52-12](https://user-images.githubusercontent.com/37603562/39403696-805527a2-4b71-11e8-8b39-96b79f4ea88c.png)

This is an official version?

**Comment by LoungeKatt** [comment]
It is an official version, but the [0dba81b] refers to a hashtag for referencing how recent the build was compared to the source. That build refers to https://github.com/reicast/reicast-emulator/commit/0dba81b99abcf909937d6473bb7e5fc83bf33e6d, which is from Oct 1, 2014. There is a good chance the issue may have been resolved, since it is nearly 4 years old.

**Comment by Jinzombie** [comment]
OK Sir thank you I will close this and wait for the official update in PlayStore hopefully 😇

**Comment by LoungeKatt** [comment]
You can also get more recent test builds from http://builds.reicast.com/

**Comment by Jinzombie** [comment]
I try build a50861b but the issue of touch controller in KOF The Evolution still there :(
