### ISSUE TITLE
Proposal: Post #emudrama licensing changes, Non profit invitation

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1648]
Hello Team,

After several discussions I think it's important to start doing the license changes, as a way to defuse the current situation. I'm tired of people trying to misread my intentions regarding licensing reicast, and all of the CLA-triggered drama.

**Proposal 1**: Code > 1 year old, as determined by commit timestamps, will be BSD 3-clause licensed.

**Proposal 2**: Code < 1 year old will be licensed by a modified BSD 4-clause license, to include a blacklist

**Proposal 3**: To get a new entry in the black list, there should be a general consensus between the maintainers team, the active developers at that time, and hopefully from past-active developers that have contributed significant amounts of code.

**Proposal 4**: Update the CLA to make it clear that the CLAs to me are only a temporary step, and I only hold them to guide the project during the transition to the non-profit. Once the non-profit is up and running, I will assign the licenses granted to me to the non-profit.

**Proposal 5**: The non-profit will be run in direct-democrazy participatory style, with some hierarchy, and some variation of liquid democracy. I'll make a more thorough proposal, but the swiss administration is a good place to study how a democracy thrives. See https://ch.ch.

**Proposal 6**: Make it clear that we /do/ want reicast integrated everywhere. If a company reaches out to us to make improvements to reicast, we make a pledge that any emulation/core fixes will make it back to the project.

**Proposal 7**: Make it clear that if we make some support contract around reicast, we will re-invest any proceeds towards the improvement of the reicast project, or any other way the members see fit.

**Invitation 1**: If you're interested in being part of the non profit verein board, or a founding member, please make a post here or reach to me at skmp@emudev.org. There will be some minimal membership costs to cover the cost of having an @emudev.org email and such, and you will have voting powers.

Thoughts?

---
Also related: #1631 #455 #407

**Comment by skmp** [comment]
For **4** I think I should also extend the CLAs to the maintainers team and not directly to me, to make this more balanced

**Comment by skmp** [comment]
Also #1649

**Comment by davidgfnet** [comment]
Proposals 4-7 LGTM
Invitation 1 also potentially good to me :)

However: what is the advantage of BSD over any other license (particularly GPL)?
I see that companies are scared of GPL, and I hope they keep that way :D, but with BSD any company, even SEGA (why not!), could just take this and release games (for which they have licenses) and we won't even hear about them. We might even go oblivious of them using reicast cause let's face it, not everyone goes reversing all re-releases to figure out whether they are new builds or just emus. I don't mind other people making profit for this within some reasonable limits, but at least I find it reasonable that if they do they either: pay back the project somehow (I don't want any money myself, at all, please no donations to me) and/or contribute back via code.

Therefore I have a counterproposal that (IMHO ofc!) fixes some of the issues while keeping the goals:

Use GPL by default. State it clearly that we are open to companies using reicast. If a company approaches us (or we could even approach them) we can (by reaching agreement by voting in the Verein) re-license them a copy of reicast under the conditions we see better fit. This allows us to fullfill Proposal 6 (were it states "we make a pledge that any emulation/core fixes will make it back to the project") by potentially getting them a license that ask for critical bugfixes to be released back to us. That can be cool to get some fixes for some games.

Also: what is the purpose of the blacklist? Didn't get that really. You mention a blacklist but don't state what happens if an org. gets blacklisted. They can't use the source at all? Only under some other license? I'm curious, both what are the implications and who you think it would be valuable to apply this blacklist to. I guess explaining one of them uncovers the other :P

**Comment by hizzlekizzle** [comment]
I don't really have a stake in this discussion so feel free to ignore, but I agree with david in suggesting that, if there's a CLA in place and a voting body that wields that power, there's no benefit to relicensing to default BSD but much risk (if you see closed source and/or commercial forks without attribution or compensation as risks). That is, the organization could vote at any time to spin off a fork with whatever license to whatever company, but you at least avoid silent exploitation as the default.

**Comment by skmp** [comment]
Personally, I'm fine with closed source / commercial forks for 1+ year old code. Long term, I think it's best for everyone for the code to be under BSD.

@davidgfnet if an org/person gets blacklisted, they can't use any new code in the repo, after the blacklist day. We could make it a 'revocable' license, but that would require more lawyer consultation.

It is meant to give some soft power against projects that are hard to work with, as well as toxic companies/closed forks/etc.

Re BSD + pledge vs GPL + permission -> Personally I prefer to operate in a "trust first, oops if people suck" principle, and that's why I prefer it.

I do want reicast to be embedded in as many places as possible, and in most cases people won't ask to license a GPL project.

There's also the side part that I've been blamed so much on trying to profit off this, that I'm wary of directly offering such services. Maybe I'm just too wary?

We could have a declaration and a simple contract that gets auto granted for non-gpl, with a revocation clause if they fail to meet the terms.

How about that + BSD for 1yr + code, and GPL for newer code?

**Comment by skmp** [comment]
(soft power - eg if there's a GPL emu that consistently imports our code, but doesn't release any of their fixes in BSD so we can merge, then we have some soft power to even the level field)

**Comment by barbudreadmon** [comment]
**Important notice :**

Naomi improvements (crypted roms support, real atomiswave, inputs, ...) was mostly ported to flycast from MAME by either @flyinghead or me as permitted by the GPL license (on a sidenote, a lot of my code was backported to your repo without me signing the CLA). Afaik, it includes any naomi improvement apart from my 2 commits on your repo last year (https://github.com/reicast/reicast-emulator/commit/2e8a87cbdf2b84d540240efa21ce714958842aca and https://github.com/reicast/reicast-emulator/commit/8e7b6b72e13555238910529153815539df718bc6).

We are not the rights holder for any code ported from MAME, and you need authorization from the real rights holder to re-license code (if you wanna try, you might start by asking @p1pkin about this). Actually it might be a good idea to check if all code committed through your CLA was committed by its real author (since it's needed and obviously not always the case here), and revert it otherwise.

**Comment by skmp** [comment]
@barbudreadmon if such code has made it in the project, then that is a violation of the cla. My understanding is that the violation/liability is with the person that did the pr, not with the project itself.

I’ll take a look in the commits you pointed, and please let me know if you know of others. I assumed people read the cla so far, and understood it’s implications. Looks like this was not the case.

GPL gets violated all the time - people that want to profit off your code will find ways to do it. GPL disallows companies to embed this within their larger projects, no matter if they improve the code or not.

Maybe LGPL/AGPL could satisfy everyone? have to check them out, been a while.

@p1pkin what do you think about all that?

**Comment by barbudreadmon** [comment]
> I assumed people read the cla so far, and understood it’s implications

That's the main issue with this CLA thingy, i don't think any contributor signing it ever thought you would change license. There is no liability in porting GPL code to another GPL project, but it might be a grey zone when there is a CLA, though in this case the backporting was done on the fork with no CLA, and i guess it was merged in your repo when you decided to merge all of @flyinghead's improvements here.

> please let me know if you know of other

I know at least another one, check the headers there : https://github.com/reicast/reicast-emulator/blob/master/core/hw/arm7/arm-new.h

**Comment by skmp** [comment]
Oh yeah, the arm code. That one is known. There are a few other small pieces that we don't have under CLA or have direct copyright over it, and of course those will remain GPL. It'll take a while to transition fully, and for example code like tests or debugger can remain GPL indefinitely.

To get better clarity on this, I don't want people doing improvements in private forks, but I want people to be able to integrate libdreamcast/reicast/nulldc to their bigger projects (eg, a frontend) without forcing them to release their code.

I guess we could have a formal agreement to release any substancial improvements - or at least document them back to us so we can re-implement - without forcing them to release their unrelated code too.

Maybe we can extend the idea behind `make a pledge that any emulation/core fixes will make it back to the project.` to include all downstream users?

**Comment by skmp** [comment]
> That's the main issue with this CLA thingy, i don't think any contributor signing it ever thought you would change license. There is no liability in porting GPL code to another GPL project, but it might be a grey zone when there is a CLA, though in this case the backporting was done on the fork with no CLA, and i guess it was merged in your repo when you decided to merge all of @flyinghead's improvements here a few months ago.

This is well documented, see #455. I've pointed /every/ new major dev towards that ticket. I guess I should have added it in the readme and in the CLA itself to clarify things further.

The intention has been to move to BSD since the code drop in 2013, I've just had no free time. I migrated to Switzerland from Greece in 2014, and that has kept me busy.

The other contensted bits are the GLES2 renderer afair, and some parts of the sh4/arm32 JIT, as those were developed under contract(s) for 3rd parties, before reicast becoming public. I'll have to check the exact contract terms to see if those can be BSD'd as-is, but I plan to rewrite both of them anyway in the following weeks.

**Comment by barbudreadmon** [comment]
I think picotcp can't be re-licensed either

> Maybe LGPL/AGPL could satisfy everyone?

LGPL seems better than BSD to me, afaik it requires changes to the codebase to be published, while frontend stuff can stay private.

**Comment by skmp** [comment]
> I think picotcp can't be re-licensed either

Many of our 3rd party libs can't, and will stay GPL. 

> > Maybe LGPL/AGPL could satisfy everyone?
> 
> LGPL seems better than BSD to me, afaik it requires changes to the codebase to be published, while frontend stuff can stay private.

That is closer to my original intention, though I need to do a full review in them to make sure they don't have any other weird terms.

Again, for further clarity, we'll be splitting the project in two parts
- libdreamcast, providing several emulation options for the dreamcast. BSD Licensing concerns this one, and only for the /must have/ code. Tests, debuggers, profilers, etc those can be GPL. 
- Reicast, using libdreamcast, with the UI and all. This can remain GPL - it'll be "just a frontend"

Hopefully more info in #1372

**Comment by ZirconiumX** [comment]
Okay, so, here are some less well known alternatives, for better or worse.

There's the CDDL (license of ZFS), which is essentially a copyleft license that applies per-file instead of per-project like the GPL. It's not compatible with the GPL though, which is a factor that should be taken into consideration.

Alternatively, there's the MPL2 (license of Firefox). This is similar to the CDDL in terms of being copyleft per-file, but it also has a GPL-family compatibility clause which means that MPL2 code can be dual-licensed as a GPL-family license while still being under the terms of the MPL2.

**Comment by davidgfnet** [comment]
Hey there!
I forgot to suggest LGPL myself indeed, always forgetting old-good-LGPL! As
has been pointer already LGPL gives most of the advantages and almost none
of the disadvantages and seems to go well with the intention to split code
into a libdreamcast indeed. This would allow people to use a
libdreamcast.dll/so and potentially make frontends and whatnot but would
retrofeed any improvements back. Also I believe it's compatible with GPL
(confirm please?) but will still require to make sure that any libs we use
are ok with LGPL. I can't recall from memory but some of the libraries we
use are either BSD or LGPL right?

I haven't really explored any other licenses, but there's many out there,
perhaps there's some better suited as some others have already proposed.

**Comment by snickerbockers** [comment]
Just droppong in to point out that if you guys are still considering the blacklist outlined in proposals 2 and 3 in the OP,  then LGPL won't work because LGPL cannot be revoked.  Version 3 of the GNU GPL states:

`All rights granted under this License are granted for the term of copyright on the Program, and are irrevocable provided the stated conditions are met.`

The GNU LGPL defines itself as a modified version of the GPL with additional permissions and exemptions.  This does not include a removal of the irrevocability clause of the GPL, so the LGPL would not be compatible with the blacklist.

Sources:
https://www.gnu.org/licenses/gpl-3.0.html
https://www.gnu.org/licenses/lgpl-3.0.en.html

**Comment by skmp** [comment]
The blacklist doesn’t need a revocable license - it can only apply for future changes. However, i do not know if you can have exempted prople/groups from gpl

**Comment by skmp** [comment]
Thinking a bit more on this

- The blacklist idea could be kept in the drawer for now. As many have pointed out it's mostly a symbolic thing than actually enforceable
- LGPL w/ linking exception seems to be a good choice, allowing integrations while requiring core changes/improvements to be published
- The auto BSD idea is also probably best left in the drawer, as it's too complex for no real benefit atm.

I'll update the proposals and maybe we can roughly vote/agree on them?

Any further comments?

**Comment by vilhelmgray** [comment]
An important nitpick: GPL/LGPL do not require changes to be made public in the sense of "the general public"; those licenses only require that the source code of the binary be provided to the user.

This means that the following scenario is completely permissible for a GPL project:
* _Alice_ creates a GPL project called **Foo**
* _Bob_ forks **Foo**, improves it with new code, and rebrands it under the new name **Bar**
   - Note: **Bar** must still be licensed under a GPL-compatible license
* _Carl_ purchases **Bar** from _Bob_
    - _Bob_ is required to provide to _Carl_ the full source code for **Bar**
    - _Bob_ is not required to publish the source code for **Bar** to the general public
    - _Carl_ is not required to publish the source code for **Bar** to the general public
    - _Carl_ is required provide the source code to anyone he distributes **Bar**
* _Alice_ is not entitled to the source code for **Bar**
    - Unless _Alice_ is given **Bar** by someone (who must then provide the **Bar** source code)
* _Alice_ may never be aware of the existence of **Bar**

**Comment by davidgfnet** [comment]
Further comments from me if I may :)
After seeing all the comments here and checking a bit dependencies and what not (every time we bring this topic we discover yet another file/code-bit that was created by someone else under who knows which license) I think reicast is a license hell :D 
I mean this in the way that I hardly believe any company would ever license it given how complex the licensing could be and how many unexpected license claimants could show up if they really mind to it, right?
So skmp I understand your willingness to be friendly to companies that might want to license the project in exchange for money and/or contributions, however most sane companies (especially big ones) will stay away after seeing that the whole license situation is dubious.
Of course this is a feeling but in the companies I worked in the past they were very conservative and only take things that they could know for sure where legit and almost risk-free.
Again this is just my view, and that's more or less my basis to say (as I previously mentioned in other channels) that staying GPL is probably the best course of action and that re-licensing it when the opportunity presents is a headache for the future to have (or perhaps never if it never happens, so let's not worry about "what-ifs").

**Comment by skmp** [comment]
I’d rather have a code audit and cleanup the licensing - reimplementing
isnt that hard.


Again, legally, for code merged by contribs the liability stays with them,
just like the liability with companies trusting emudev.org / reicast lies
with us, not them.

Code cleanup and licensing cleanup are clearly in order methinks

**Comment by vilhelmgray** [comment]
A code audit is necessary anyway in order to ensure that no infringements are occuring. Even if the Reicast project is protected from liability due to the CLA, the infringing code would still need to be removed if discovered.

So it's better to do that before an infringement case is brought up, while we have the time to address it and to reimplement the respective problem code, rather than to rush to replace infringing code once it is unexpectedly brought up.

**Comment by Holzhaus** [comment]
I've been inactive for year, so I don't think I have much say here ;-) Anyway, I'm fine with relicensing the code as LGPL, but IMHO the split-off emulation library shouldn't be named "libdreamcast". Dreamcast is a registered trademark, so it needs some other name like "libreicast" or "libfantasystream" (vs . "Dreamcast" which comes from "Dream Broadcast") or something like that.

**Comment by skmp** [comment]
libfantasticast?

Good point about the trademark. I wanted libdc but it’s taken :|

**Comment by skmp** [comment]
> A code audit is necessary anyway in order to ensure that no infringements
> are occuring. Even if the Reicast project is protected from liability due
> to the CLA, the infringing code would still need to be removed if
> discovered.
>
Agreed.

So it's better to do that before an infringement case is brought up, while
> we have the time to address it and to reimplement the respective problem
> code, rather than to rush to replace infringing code once it is
> unexpectedly brought up.
>
Also agreed

**Comment by davidgfnet** [comment]
So if we decide to settle for GPL (not sure if that's what you proposed skmp) should we try to bring some people back to the project? You know :)

**Comment by vilhelmgray** [comment]
The proposal is to switch to the LGPL (Lesser GNU Public License) for the Reicast library (name currently pending, but perhaps libreicast?). The main difference between this and the GPL is that LGPL code is allowed to be used in non-GPL-compatible projects without forcing a change in said projects' licenses -- only the LGPL code and changes to it are bound by the traditional GPL requirements (i.e. sharing of source code, freedom of use, etc.).

Switching to LGPL should make libreicast a lot friendly to non-GPL-compatible projects and companies, while still keeping the traditional benefits of the GPL so that improvements of the libreicast code can be merged back to us.

**Comment by skmp** [comment]
Yup, LGPL + linking exception, precisely to make integration easier.

As for the name, I'd rather avoid using `libreicast`. If we want to make a general dreamcast emulation library it shouldn't be attached to reicast like that. I'd love for contributors of other projects to join in too, and I think using a more generic name will also help.

Maybe the name should be a separate ticket?

**Comment by vilhelmgray** [comment]
Yes, a separate ticket for the naming would be a good idea so that the naming discussion doesn't get confused with licensing talk -- the library needs a name regardless of the license chosen.

**Comment by skmp** [comment]
Follow up for the non-profit: https://github.com/emudev-org/emudev.org/issues/10 << bylaws and structure proposal

**Comment by baka0815** [comment]
As long as my name stays in the git history, so I can brag being a part of reicasts history, I don't care how you're re-licensing my code as long as it stays open source.

**Comment by skmp** [comment]
We've switched to BSD3. Will reconsider if abuse happens.

**Comment by barbudreadmon** [comment]
As i already said, you can't change license on backported stuff, it is illegal, you never got the real authors to sign your CLA. It includes pretty much every naomi enhancements from the past 2 years.

**Comment by skmp** [comment]
@barbudreadmon I scanned the src code and saw some BSD-3clause mentions in that code, so I assumed it was under BSD (like most of mame?).

Otheriwise we can just mark them under GPL -- or their correct license if that is not the right one.

Can you point out relevant files + correct license? Some of the naomi work is from nulldc, and I'm not exactly clear on what is what.

**Comment by skmp** [comment]
(Each file in CORE has an `#include <license/bsd>` or `#include <license/gpl>` right now)

**Comment by Holzhaus** [comment]
> (Each file in CORE has an `#include <license/bsd>` or `#include <license/gpl>` right now)

How about using [SPDX License Identifiers](https://spdx.org/ids) 
instead of `#include`'ing the license text?

**Comment by barbudreadmon** [comment]
Those 2 are LGPL : 
https://github.com/mamedev/mame/blob/master/src/mame/drivers/naomi.cpp
https://github.com/mamedev/mame/blob/master/src/mame/machine/naomi.cpp

Pretty much all other naomi/aw related files in MAME are BSD indeed :
https://github.com/mamedev/mame/blob/master/src/mame/machine/315-5881_crypt.cpp
https://github.com/mamedev/mame/blob/master/src/mame/machine/naomigd.cpp
https://github.com/mamedev/mame/blob/master/src/mame/machine/naomim1.cpp
https://github.com/mamedev/mame/blob/master/src/mame/machine/naomim2.cpp
https://github.com/mamedev/mame/blob/master/src/mame/machine/naomim4.cpp
...

I might be missing some files, but basically i think the encryption part is BSD while the part that binds everything together is LGPL. Commit history is unclear with your changes, so it's kinda hard to track the involved files, but i think both naomi.cpp & naomi_cart.cpp contain LGPL code backported from MAME.

**Comment by skmp** [comment]
Alright.

@Holzhaus I'm not opposed to it in addition to the includes. The includes have logic to enforce the license via #error, so you can build a BSD-only build. Not all modules can do that /yet/, but that is a goal.

**Comment by skmp** [comment]
@barbudreadmon 
Yes, going on the comment there
`This file is a mix of my code, Zezu's, and duno wtf-else (most likely ElSemi's ?)` that makes sense. I think it was originally somewhat plagiarized from chankast tbh. Like the mmap idea is clearly from there, I recall implementing that.

`naomi_cart.cpp` I do not recognize. I guess only @flyinghead knows where it came from.

I'll mark them both LGPL w/ a note that they are probably based on mame. 
Sounds good?

**Comment by skmp** [comment]
@barbudreadmon I meant to PR but failed at git. https://github.com/reicast/reicast-emulator/commit/c0eaa4a003e5d36d180d81220c3ee4ad1d254a1a is in alpha

**Comment by barbudreadmon** [comment]
> Sounds good?

Yes

**Comment by skmp** [comment]
And with that I guess we can close this.
