### ISSUE TITLE
Evolution 2: Far Off Promise crash

### ISSUE THREAD

**Issue by SquidInvasion** [reicast/reicast-emulator#168]
After the first battle and you talk to the character to engage the cutscene the game crashes and returns you to the main reicast menu.

This has been tested with new builds from Loungekat's buildbot for Android, I'm not sure how it fares with other versions but on Android the game crashes in that exact spot each time so far.

**Comment by DaymonEng** [comment]
So, I know that this thread is old, but I'd like to put a bandaid on this issue. I'm unsure if this is relevant as far as fixing the crashing problem in Evolution 2: Far Off Promise, but I know that for those who are interested in at least getting past the initial crash that follows the first fight on the train that this will help.
In order to do this you'll need to download:
NullDC (https://www.emuparadise.me/Sega_Dreamcast_Emulators/Windows/NullDC/39)
& Evolution 2: Far Off Promise.gdi/.cdi
First you'll need to format the vmu in NullDC by selecting normal boot, no disc, click on the vmu icon, and delete all on the vmu that has a red x on it, thereby formatting it.
Then, boot up Evolution 2, and once you get past the train cutscene and are able to walk around the town, save the game and exit NullDC
There are two methods to go from here, if you have an empty vmu or only one vmu currently made in reicast follow procedure 1, if you don't then follow procedure 2.
1.) Go to the root NullDC folder, there will be a file called "vmu_data_port01.bin", copy this file. Go to the storage folder on your phone where you have your reicast vmu files (assuming you created them) and delete the empty vmu (unless you only have one) then rename "vmu_data_port01.bin to "vmu_save_A2.bin"
2.) Download Chankast (http://www.emulator-zone.com/doc.php/dreamcast/chankast.html), once downloaded, in the zip folder there will be a file called "vmsbrowser.exe", extract this file to the root NullDC folder.
(Note: this can get confusing)
-Rename "vmu_data_port01.bin" to "vms.bin"
-Open up "vmsbrowser.exe" and click "Reload VMS.BIN"
-Your save game should pop up as "EVO2_DAT.001" with Linear's face on it. Click the save, then click "Export .DCI", it will be in the root NullDC folder.
-Rename "vms.bin" back to "vmu_data_port01.bin"
-Get the vmu for Reicast on your phone that you have save data and cut it to the NullDC folder (either "vmu_save_A2" or "vmu_save_A1")
-Rename it to "vms.bin"
-Open up "vmsbrowser.exe" and click "Reload VMS.BIN", then click "Import Save" and choose "EVO2_DAT.001.DCI"
-Close out of "vmsbrowser" and rename your vmu to either "vmu_save_A2" or "vmu_save_A1" (whichever it was before)
-Cut and paste your vmu save file back to the Reicast storage folder.
NOW,
Open up Reicast, boot up Evolution 2, and load up the save game, you'll be able to continue from there on out. Any further issues regarding crashes from cutscenes and such you can use the same technique and use NullDC to progress past the cutscene then save.
I hope this helps, at least putting a bandaid on the issue until it gets fixed (if it ever does) :)

**Comment by magistery0** [comment]
Do you have a copy of this bypassed save file? It would be a huge help if you could share it.
Also thanks for the tips and tricks, it'll be pretty darn useful for those who does have a PC.

**Comment by DaymonEng** [comment]
Here you go! Just unzip the zip folder and use the vms browser to input the save file, this will take you in front of the hotel right after the train. :)
[EVO2_DAT.001.zip](https://github.com/reicast/reicast-emulator/files/728011/EVO2_DAT.001.zip)

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#36
