### ISSUE TITLE
Crash in Skies Of Arcadia on r5, r6

### ISSUE THREAD

**Issue by hubrisnxs** [reicast/reicast-emulator#250]
I just found out about the newer builds, including the error log, so I decided to leave said log. This occurs on any device I've used, this from my s4 at 4.2.2 though it occurs at same event on my Mali tablet. As soon as the air battle with the first use of hookshot is finished, after experience/item gained screen, it crashes out of app....  although not causing a boot loop like the Grandia 2 one I'm going to submit in a few minutes. Any explanations of why they occur would be wonderful (though I've believe I've tried everything, different roms save files etc)

**Comment by chopchopmastereric** [comment]
https://mega.co.nz/#!n9giQBZa!d3iY4k8uBaM03C1VkQ0VtuedisnhCueIhMNddSGYAXs 

This it's the vmu save file for continue playing after the crashing area

**Comment by hubrisnxs** [comment]
Sorry, I, missed the request for a continuance and save file. 

Word has it that Shenmue and Grandia work. I'm on a Lg pad 8.3 tablet that uses Adreno for some reason. I'm told the latest builds don't work, can I get a recommendation for a build to use? The store version just goes black for me, both on this tablet and my Galaxy Note 3

**Comment by magistery0** [comment]
the force exit bug is still not fixed yet...

**Comment by skmp** [comment]
@magistery0 thx for the update, i'll put it on the list of game-fixes to do for r8 :)

**Comment by Moonmadness** [comment]
Talking about SoA errors, at some point in the game I had a popup telling "Reicast error : Verify failed : !" and some "jna" thing (sorry, I tried to make a screenshot a few times but it disappeared too quickly). The game didn't crash or exit but in the sequence when you get on the Delphinus for the first time it reeeeally slows down your game until you're in the ship battle against the door. Unfortunately I don't have the save file anymore, but maybe it rings a bell.

**Comment by Moonmadness** [comment]
I finally managed to write down the error message:

Emulator Error:
Verify Failed : !
IsModVolList(ta_fsm_cl)
in ta_handle_cmd -> jni/../
jni/../../../core/hw/pvr/ta.cpp : 242

It triggered one last time at the beginning of the battle against the final boss.

**Comment by Dio94** [comment]
Hi,

My problem was different but concerned the same game.
My game was freezing after a couple of time (randomly around 20/30 minutes).
And I tried your last build from http://builds.reicast.com/ 
( 73a585a	2015-10-09T10:21:39.000Z	).

Now i have been able to let the game play for more than an hour without freezing the app or even the phone like it did before.

I'll copy paste this to the original issue I was following, but i needed to report the good news!

**Comment by sabula310** [comment]
but to tail you can you fix the reicast verison error the one you have in
google playstore

**Comment by jlozes** [comment]
This error is not fixed in the last build ( ), the game crash after this battle.

Something strange also, the first time that I have tried to past this moment, the game has not crashed. A crash has occured two or three minutes after that moment and I had not saved. Now, when I try to pass this moment, the game crash evry times.

I've tried with differents pal versions of the game, CDI or GDI versions, normal 50 HZ and 60 HZ hack. I've also tried to change options of the emulator, (region, display type, cable type, dynareg, force software, instable optimisation..., I think I have tried evry combinations) and I have also tried with different bios but same issue.

Here is the logcat when the emulator crash:

"
1-13 03:29:10.409 18410 18873 I reicast : reicast git/n - 9.97 (0.00) - 100.27 - V: 60.11 (2.02, NTSC480i59.95) R: 29.81+0.00 VTX: 0.00 , MIPS: 0.00 
 1-13 03:29:12.460 18410 18873 I reicast : reicast git/n - 10.00 (0.00) - 100.03 - V: 59.96 (1.98, NTSC480i59.95) R: 30.22+0.00 VTX: 0.00 , MIPS: 0.00 
 1-13 03:29:14.507 18410 18873 I reicast : reicast git/n - 10.06 (0.00) - 99.45 - V: 59.62 (2.00, NTSC480i59.95) R: 29.81+0.00 VTX: 0.00 , MIPS: 0.00 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: thread Thread[22,tid=18872,Native,Thread*=0x51fe3200,peer=0x13403f80,"GLThread 238"] using JNIEnv* from thread Thread[22,tid=18872,Native,Thread*=0x51fe3200,peer=0x13403f80,"GLThread 238"] 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]     in call to NewByteArray 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]     from void com.reicast.emulator.emu.JNIdc.rendframe() 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410] "GLThread 238" prio=5 tid=22 Runnable 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x13403f80 self=0x51fe3200 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   | sysTid=18872 nice=0 cgrp=default sched=0/0 handle=0x53a03930 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 144534320896 51173733595 589248 ) utm=12249 stm=2204 core=1 HZ=100 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   | stack=0x53901000-0x53903000 stackSize=1038KB 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #00 pc 00372475  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+160) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #01 pc 00351a6b  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+150) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #02 pc 0025abd1  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+740) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #03 pc 0025b2a9  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+64) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #04 pc 000fdf29  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+32) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #05 pc 00102fcb  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE.constprop.95+4958) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #06 pc 0010d19d  /system/lib/libart.so (_ZN3art8CheckJNI17NewPrimitiveArrayEPKcP7_JNIEnviNS_9Primitive4TypeE+388) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #07 pc 0005d538  /data/app/com.reicast.emulator-1/lib/arm/libdc.so (???) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #08 pc 0004e0d4  /data/app/com.reicast.emulator-1/lib/arm/libdc.so (???) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #09 pc 00049a40  /data/app/com.reicast.emulator-1/lib/arm/libdc.so (???) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #10 pc 0001cfb8  /data/app/com.reicast.emulator-1/lib/arm/libdc.so (???) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #11 pc 00042910  /data/app/com.reicast.emulator-1/lib/arm/libdc.so (???) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #12 pc 0005d9b0  /data/app/com.reicast.emulator-1/lib/arm/libdc.so (???) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #13 pc 0013dae5  /data/app/com.reicast.emulator-1/oat/arm/base.odex (void com.reicast.emulator.emu.JNIdc.rendframe()+72) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #14 pc 00130a09  /data/app/com.reicast.emulator-1/oat/arm/base.odex (void com.reicast.emulator.emu.GL2JNIView$Renderer.onDrawFrame(javax.microedition.khronos.opengles.GL10)+196) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   native: #15 pc 00e01c87  /data/dalvik-cache/arm/system@framework@boot.oat (???) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   at com.reicast.emulator.emu.JNIdc.rendframe(Native method) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   at com.reicast.emulator.emu.GL2JNIView$Renderer.onDrawFrame(GL2JNIView.java:573) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410]   at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240) 
 1-13 03:29:16.846 18410 18872 F art     : art/runtime/java_vm_ext.cc:410] 
 1-13 03:29:17.005   243   806 I AudioFlinger: BUFFER TIMEOUT: remove(4097) from active list on thread 0x47f60000 
 1-13 03:29:19.477   243   806 E nvaudio_hw: disable_snd_device:  snd_device ref cnt is already 0 
 1-13 03:29:27.150 18410 18872 E art     : Unexpected time out during dump checkpoint. 
 1-13 03:29:27.150 18410 18872 F art     : art/runtime/barrier.cc:90] Check failed: count_ == 0 (count_=1, 0=0) Attempted to destroy barrier with non zero count 
 1-13 03:29:27.150 18410 18872 F art     : art/runtime/runtime.cc:372] Runtime aborting --- recursively, so no thread-specific detail! 
 1-13 03:29:27.150 18410 18872 F art     : art/runtime/runtime.cc:372] 
 1-13 03:29:27.151 18410 18872 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 18872 (GLThread 238) 
 1-13 03:29:27.253   240   240 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
 1-13 03:29:27.253   240   240 F DEBUG   : Build fingerprint: 'NVIDIA/foster_e_hdd/foster:6.0/MRA58K/324774_793.8284:user/release-keys' 
 1-13 03:29:27.253   240   240 F DEBUG   : Revision: '0' 
 1-13 03:29:27.253   240   240 F DEBUG   : ABI: 'arm' 
 1-13 03:29:27.253   240   240 F DEBUG   : pid: 18410, tid: 18872, name: GLThread 238  >>> com.reicast.emulator <<< 
 1-13 03:29:27.253   240   240 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr -------- 
 1-13 03:29:27.273   240   240 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: thread Thread[22,tid=18872,Native,Thread*=0x51fe3200,peer=0x13403f80,"GLThread 238"] using JNIEnv* from thread Thread[22,tid=18872,Native,Thread*=0x51fe3200,peer=0x13403f80,"GLThread 238"]' 
 1-13 03:29:27.273   240   240 F DEBUG   :     r0 00000000  r1 000049b8  r2 00000006  r3 53a03978 
 1-13 03:29:27.273   240   240 F DEBUG   :     r4 53a03980  r5 53a03930  r6 0000006e  r7 0000010c 
 1-13 03:29:27.273   240   240 F DEBUG   :     r8 4305c840  r9 4305ae6c  sl 00000050  fp 43040730 
 1-13 03:29:27.273   240   240 F DEBUG   :     ip 00000006  sp 53a02650  lr 40383331  pc 403848f8  cpsr 40070010 
 1-13 03:29:27.285   240   240 F DEBUG   : 
 1-13 03:29:27.285   240   240 F DEBUG   : backtrace: 
 1-13 03:29:27.285   240   240 F DEBUG   :     #00 pc 000418f8  /system/lib/libc.so (tgkill+12) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #01 pc 0004032d  /system/lib/libc.so (pthread_kill+32) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #02 pc 0001ca6f  /system/lib/libc.so (raise+10) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #03 pc 00019c21  /system/lib/libc.so (__libc_android_abort+34) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #04 pc 000174e4  /system/lib/libc.so (abort+4) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #05 pc 00334851  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+228) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #06 pc 000f534d  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2240) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #07 pc 000f161d  /system/lib/libart.so (_ZN3art7BarrierD2Ev+216) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #08 pc 0035cacb  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+162) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #09 pc 00334915  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+424) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #10 pc 000f534d  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2240) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #11 pc 0025aefb  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1550) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #12 pc 0025b2a9  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+64) 
 1-13 03:29:27.285   240   240 F DEBUG   :     #13 pc 000fdf29  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+32) 
 1-13 03:29:27.286   240   240 F DEBUG   :     #14 pc 00102fcb  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE.constprop.95+4958) 
 1-13 03:29:27.286   240   240 F DEBUG   :     #15 pc 0010d19d  /system/lib/libart.so (_ZN3art8CheckJNI17NewPrimitiveArrayEPKcP7_JNIEnviNS_9Primitive4TypeE+388) 
 1-13 03:29:27.286   240   240 F DEBUG   :     #16 pc 0005d538  /data/app/com.reicast.emulator-1/lib/arm/libdc.so (offset 0x7af000) 
 1-13 03:29:27.751   240   240 F DEBUG   : 
 1-13 03:29:27.751   240   240 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_04 
 1-13 03:29:27.751   240   240 E DEBUG   : AM write failed: Broken pipe 
 1-13 03:29:27.753   735  1061 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE) 
 1-13 03:29:27.780   735 19560 W ActivityManager:   Force finishing activity com.reicast.emulator/.GL2JNIActivity 
 1-13 03:29:27.852   735   744 I art     : Background sticky concurrent mark sweep GC freed 78587(4MB) AllocSpace objects, 16(1408KB) LOS objects, 17% free, 26MB/32MB, paused 14.150ms total 97.264ms 
 1-13 03:29:27.866   735  1837 W InputDispatcher: channel '8163e6e com.reicast.emulator/com.reicast.emulator.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9 
 1-13 03:29:27.867   735  1837 E InputDispatcher: channel '8163e6e com.reicast.emulator/com.reicast.emulator.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed! 
 1-13 03:29:27.867   735  2940 I WindowState: WIN DEATH: Window{10e9ef1 u0 SurfaceView} 
 1-13 03:29:27.868   735  1045 D GraphicsStats: Buffer count: 5 
 1-13 03:29:27.872   735  1044 I WindowState: WIN DEATH: Window{8163e6e u0 com.reicast.emulator/com.reicast.emulator.MainActivity} 
 1-13 03:29:27.872   735  1044 W InputDispatcher: Attempted to unregister already unregistered input channel '8163e6e com.reicast.emulator/com.reicast.emulator.MainActivity (server)' 
 1-13 03:29:27.880   735  2852 I WindowState: WIN DEATH: Window{4fd2732 u0 com.reicast.emulator/com.reicast.emulator.GL2JNIActivity} 
 1-13 03:29:27.907   735  6063 I OpenGLRenderer: Initialized EGL, version 1.4 
 1-13 03:29:27.918   256   256 I Zygote  : Process 18410 exited due to signal (6) 
 1-13 03:29:27.918   735  2301 I ActivityManager: Process com.reicast.emulator (pid 18410) has died 
 1-13 03:29:27.937   735  2301 I ActivityManager: Start proc 19564:com.reicast.emulator/u0a122 for activity com.reicast.emulator/.MainActivity 
 1-13 03:29:27.947 19564 19564 I art     : Late-enabling -Xcheck:jni 
 1-13 03:29:27.961  2806  2806 D ShieldTech_Services: Starting service 
 1-13 03:29:27.966  2806  2806 E ApplicationPackageManager: android not found in CATEGORY_LEANBACK_LAUNCHER 
 1-13 03:29:27.966  2806  2806 D RSMouse : mFeatureEnabled=true  mPackageEnabled=false 
 1-13 03:29:27.980   735  2855 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true 
 1-13 03:29:27.997   735  2889 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true 
 1-13 03:29:28.252 19564 19564 W linker  : /data/app/com.reicast.emulator-1/lib/arm/libdc.so has text relocations. This is wasting memory and prevents security hardening. Please fix. 
 1-13 03:29:28.258 19564 19564 I reicast : Config dir is: /sdcard/jeux/dreamcast/ 
 1-13 03:29:28.258 19564 19564 I reicast : Data dir is:   /sdcard/jeux/dreamcast/ 
 1-13 03:29:28.283 19564 19564 W PhoneWindow: Previously focused view reported id 2131361804 during save, but can't be found during restore. 
 1-13 03:29:28.292 19564 19583 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true 
 1-13 03:29:28.362 19564 19583 I OpenGLRenderer: Initialized EGL, version 1.4 
 1-13 03:29:28.470   735  1063 W WindowAnimator: Failed to dispatch window animation state change. 
 1-13 03:29:28.470   735  1063 W WindowAnimator: android.os.DeadObjectException 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:542) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:742) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:97) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: Failed to dispatch window animation state change. 
 1-13 03:29:28.470   735  1063 W WindowAnimator: android.os.DeadObjectException 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:542) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:742) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:97) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61) 
 1-13 03:29:28.470   735  1063 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46) 
 1-13 03:29:28.489   735  1063 I ActivityManager: Displayed com.reicast.emulator/.MainActivity: +568ms 
 1-13 03:29:31.401   735  6063 D OpenGLRenderer: endAllStagingAnimators on 0x2052df1c00 (RippleDrawable) with handle 0x2052e2c600 
 1-13 03:29:31.407  2806  2806 D RSMouse : mFeatureEnabled=true  mPackageEnabled=false 
 1-13 03:29:31.407   735  2940 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 18410 uid 10122 
 1-13 03:29:31.573   735  1063 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0

"

I will try with an other save and if it doesn't work I'll try to make the game again until this moment without saving and see. I will also try to save in an other area of the game before reaching this moment and see if the bug occure. I'll edit this message when these tests will be done.

Maybe I'll test with NTSC version but I'm not very intrested to do the game in US. If I do it, I will post the result of this test to.

My device is an NVIDIA Shield TV with Android 6, the firmware 3.3. The controler used for the test is a PS3 controler connected via USB.

**Comment by Ginger933** [comment]
I'm having the same problem tried the vmu linked above. Reicast wouldn't recognize it. What can I do. I'm on a moto E
