### ISSUE TITLE
Resident Evil: Code Veronica random crash

### ISSUE THREAD

**Issue by helloray** [reicast/reicast-emulator#254]
Version: Lastest git version
Devices: 1.2ghz Dualcore Snapdragon Adreno 203 and Exynos 4 Quad 4412(Galaxy S3)

result = Often Sudden Return to Emu's Game Browser.
I played about 5-15mins, then it goes back to emu menu all of sudden. 
Tried many times, the results were similar. 

cfg
Dynarec.Enabled=1
Dynarec.unstable-opt=0

I also tried the x86 version reicast(built by myself). it seems much more stable than the arm version.

**Comment by skmp** [comment]
@Sephkateno @helloray can either of you re-test this with latest master?

**Comment by Sephkateno** [comment]
I don't think it needs testing mate have played the entire game with no
crashes it was an early build problem i guess(it used to crash on me after
ten fifteen minutes) but if you really want to i guess i could. In this
case can you send me a link of the latest build you want me to test?

**Comment by skmp** [comment]
There you go, [dfc58ec](http://reicast-builds.s3.amazonaws.com/builds/heads/master-dfc58ec/reicast-android-debug-dfc58ec.apk)

**Comment by Sephkateno** [comment]
Alright tested on two devices Samsung Galaxy S7 edge exynos and nexus 6p no
random reboots this time around but very buggy. Frames stuttering, sound
effects like rain stopping and restarting like on a loop, on the menu many
settings were not adjustable like they were in the past and the opening
movie scene was stuttering like hell. I didn't know which issues were
caused by framedrop and which weren't i could not check fps on screen. On
s7 edge there was less framedrop obviously but almost all issues were there
too. I will send some pics. The log link is
http://loungekatt.sytes.net:3194/ReicastBot/report/logs/1523565414176.txt

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#66
