### ISSUE TITLE
Add support for Save States

### ISSUE THREAD

**Issue by hooby3dfx** [reicast/reicast-emulator#301]
We cant go to the background running (https://github.com/reicast/reicast-emulator/issues/152) so the next best thing would be to save (like Mupen64). 

...Just realized that nulldc/no other dc emu has this. 

Long term goal!

**Comment by AbandonedCart** [comment]
Closing this now that background functionality is supported. This can be reopened if it becomes more realistic and still required later.

**Comment by blackman91** [comment]
It seems save states just became a lot more realistic, the libretro reicast port now has savestate functionality:
https://www.reddit.com/r/emulation/comments/9asb0v/reicast_libretro_updates_savestate_support_and/

Hope they can port it to standalone too.

**Comment by AbandonedCart** [comment]
It relies on libretro's proprietary luts code.

**Comment by blackman91** [comment]
https://github.com/reicast/reicast-emulator/pull/1367

**Comment by AbandonedCart** [comment]
This is not compatible **yet** but that commit does provide 95% of the required code to include it (because it does not include all of the UI changes). The PR did port some of the code that was required to get it running, but there is still some verification needed that it doesn't change anything outside the scope of adding save states.
