### ISSUE TITLE
Maple: Support jump pack

### ISSUE THREAD

**Issue by hooby3dfx** [reicast/reicast-emulator#340]
http://en.wikipedia.org/wiki/Dreamcast_accessories#Jump_Pack

I GOT THIS

**Comment by Holzhaus** [comment]
We should probably split this task up since it there are basically two things to do:
- Get rumble/jumppack support at the emulator side and write it into a variable (like these `kcode`, `joyx`, `joyy`, etc. variables) or using a callback function. This is something I can't do, since I don't have in-depth knowledge about dreamcast internals.
- Handle the rumble events on the OS side. I'd volunteer and implement this on Linux (evdev).

**Comment by skmp** [comment]
Yeh, it needs a new callback. Ill look on the emulation side when i have
some more time, it is trivial to add
Am 24.08.2015 13:50 schrieb "Jan Holthuis" <notifications@github.com>:

**Comment by Holzhaus** [comment]
Just stumbled upon this, could also be helpful:
http://sourceforge.net/p/cadcdev/kallistios/ci/d9c299e747991c7ba85a6c5811ac4b226b481eb0/tree/kernel/arch/dreamcast/include/dc/maple/purupuru.h

**Comment by baka0815** [comment]
This should be fixed by now and can be closed?

**Comment by AbandonedCart** [comment]
Completely missing on Android

**Comment by skmp** [comment]
@hooby3dfx I assume you no longer plan to work on this?

**Comment by baka0815** [comment]
It's also not implemented for SDL afaik (#1371).

**Comment by baka0815** [comment]
It **is** implemented in SDL code. So only backend left is Android?

**Comment by skmp** [comment]
Should be implemented after #1523
