### ISSUE TITLE
Raspberry pi port?

### ISSUE THREAD

**Issue by weihan1102** [reicast/reicast-emulator#377]
Hi, i just have a question.
Is it possible to port reicast to raspberry pi?

Sorry if it is a stupid question :P

**Comment by kingosticks** [comment]
Would this be feasible with the new Raspberry Pi 2's armv7 cortex-a7? I had a very quick attempt at building with gcc 4.8 (as that seems to support cortex-a7-NEON) but it failed with a template typing problem somewhere.. Understandably it needs more than some makefile changes to get it going but since I've only just discovered this project I'd like to know if it's even worth trying before I go any further.

**Comment by skmp** [comment]
should mostly work out of the box w/ the beagle makefile. how do you build?

On Mon, Feb 9, 2015 at 10:03 PM, Nick Steel <notifications@github.com>
wrote:

> Would this be feasible with the new Raspberry Pi 2's armv7 cortex-a7? I
> had a very quick attempt at building with gcc 4.8 (as that seems to support
> cortex-a7-NEON) but it failed with a template typing problem somewhere..
> Understandably it needs more than some makefile changes to get it going but
> since I've only just discovered this project I'd like to know if it's even
> worth trying before I go any further.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/377#issuecomment-73589631>
> .
>



-- 
~skmp

**Comment by kingosticks** [comment]
I think the beagle makefile in the master branch might be a bit out of
date. I guess the armhf one is the way to go. I did get something built but
then when trying to run it I got memory allocation failures, unhelpfully I
don't have the specific error to hand. It's probably something dumb in my
setup, I'll try again and see where I get to.

**Comment by ptitSeb** [comment]
Maybe try the Pandora makefile.

**Comment by skmp** [comment]
Let's make a new Issue for RaPi2. #601 ?
