### ISSUE TITLE
Emulator error pops up in DOA2 (unneccessarily)

### ISSUE THREAD

**Issue by hooby3dfx** [reicast/reicast-emulator#625]
**Game:** Dead or Alive 2
**Device:** Shield Portable
**Android version:** 4.4
**Reicast version:** https://github.com/reicast/reicast-emulator/commit/ebabdee
**Frequency:** Always
**Description:**
Error with info useful for devs but probably not useful to gamers appears randomly, and multiple times. Game otherwise continues to run and dismissing the errors allows gameplay to continue. 
I dont think we should ship with this enabled, unless it only shows up when games crash out. Maybe this could be a setting thats disabled by default like "Show emulator error popups". 

**Steps to reproduce:**
Let game run in attract mode for 5 minutes.  

**Screenshot:**
https://drive.google.com/file/d/0B3xeid6v2vUbZ3M5SDlTYXNlQXh2ZlNjTEYyb015ZHVxcnVZ/view?usp=sharing

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/commit/21fbad3ba50a8adc1630a70199fbf9c046b6351c

It was part of the verification of the freeze issue. It will be reverted once it is no longer needed.

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/pull/626 will return it to the toast message. Ideally, we will fix the issues so it doesn't pop up instead of needing a toggle. That way, if it does pop up users know to go send a log.

**Comment by hooby3dfx** [comment]
i get the idea, but i somehow feel that most people that get the app wont really understand what to do with the message. 
what would be killer is if we could silently report errors like this in the background to a server so we can see aggregate info.

**Comment by LoungeKatt** [comment]
It's already somewhat done but can't be silent due to Google policy. I had added a print of the error to logcat when it displayed so it gets included in the submissions.

**Comment by hooby3dfx** [comment]
You can totally beam back diagnostics info as long as you declare it in
privacy policy.

**Comment by LoungeKatt** [comment]
I got nailed for "deceptive code" doing exactly that. I think it depends on where it goes. If we used a service, they would likely be OK. It's doing it to a private server they seem to frown upon.

**Comment by skmp** [comment]
I totally agree we should have some "opt-in" way to let the users send us this kind of feedback automatically. 

This is a pretty serious bug though, and the design in nullDC was such that it was irritating to the users so I got wind of it. The problem is we have too many open bugs in the core that "mostly work okay" when ignored.

**Comment by LoungeKatt** [comment]
The bug report method we use now was only ever meant to be temporary. If I have the okay to act on behalf of reicast, I can set up something else and forward along the credentials or I can reroute it to something else set up for it. The long and short is that I can't really automate submissions to a server only acting as a failsafe because the bandwidth isn't there for it.

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/pull/637 <- This should act more like the standard prompts Google gives. I could have sworn that dialog had a report button, but it looks like it didn't. Now it does.

**Comment by skmp** [comment]
@hooby3dfx is this still an issue on current master?

**Comment by hooby3dfx** [comment]
Nope, it appears that this popup was removed at some point.
Keep up the good work guys!
