### ISSUE TITLE
FileBrowser crashes when navigating up to /data

### ISSUE THREAD

**Issue by BonzaiThePenguin** [reicast/reicast-emulator#649]
New users have to tell Reicast where the Dreamcast BIOS is located via the FileBrowser that appears when they first launch the app. There's a usability issue with it not telling them that that's what they're supposed to be doing, but more importantly it crashes if they traverse up the hierarchy to get to `/data`:

```
java.util.TimSort.sort(TimSort.java:169)
java.util.Arrays.sort(Arrays.java:2023)
com.reicast.emulator.FileBrowser.navigate(FileBrowser.java:462)
com.reicast.emulator.FileBrowser$5.onClick(FileBrowser.java:494)
android.view.View.performClick(View.java:4461)
...
```

For some reason it requires me to select a folder within `/data/media/0` and defaults to `/data/media/0/Android/data/com.ooi.android.smb2`, both of which seem to be a bit nonsensical. My device uses `/storage/emulated/0/` and `/storage/external_SD/`, not whatever the `/data` folder is. The only way I was able to get the emulator to work was to exit the FileBrowser immediately and manually type the path to the BIOS and games directories.

**Comment by BonzaiThePenguin** [comment]
If no one is available to work on this one this is something I can probably handle. I recently worked on improving the UI for Mupen64Plus-AE.

**Comment by skmp** [comment]
For some reason, that part of the UI doesn't work at all for me. I just can't pick the folder. Typing the path works.

**Comment by LoungeKatt** [comment]
/storage/emulated/0 is a symlink to /data/media/0. It was likely not working due to permission issues completely unrelated to the path, but should be resolved now.

As you can see from
https://github.com/reicast/reicast-emulator/blob/master/shell/android/src/com/reicast/emulator/config/OptionsFragment.java and https://github.com/reicast/reicast-emulator/blob/master/shell/android/src/com/reicast/emulator/FileBrowser.java the only replacement is to substitute /sdcard0 for /storage/0 which should prevent the absolute path from returning the root /data/media/0 path.

@skmp, I hadn't realized you were having issues. I don't get a chance to read every notification, so if it is something I wrote, you are welcome to tag me on the issue so I see it sooner.

**Comment by LoungeKatt** [comment]
As for the usability issue, I believe that was also resolved along the way. If not, it is a part of a new UI design I am putting together to test out that will not only better explain initial setup, but allow storing the BIOS on Google Drive and having it placed in the necessary path automatically. It is a proven fact that no amount of documentation will explain setup well enough unless the app walks you through it.

**Comment by AbandonedCart** [comment]
This is ancient history now.
