### ISSUE TITLE
Street Fighter Alpha 3 black screen

### ISSUE THREAD

**Issue by fivefeet8** [reicast/reicast-emulator#650]
Game:  Street Fighter Alpha 3 (US)  ver.1001

The game is in GDI format as below:

file.gdi
track01.bin
track02.raw
track03.bin

The game loads the Dreamcast logo then goes to a black screen.  Device is still functional, but it stays at the black screen.  I'm guessing it should be loading the Capcom intro logo, but it doesn't.  I can still exit the application like normal by bringing up the menu.

Device:  Nvidia Shield Tablet (Lollipop)
Commit Vers: 86004e687960e7aeac0af812d111d45f9932a4bc

I've tried the game on various versions in the past and none have worked as well.

**Comment by MrPsyMan** [comment]
If I recall correctly that's a timing issue with DMAs. Will take a while until fixed.

**Comment by twinaphex** [comment]
There is a way to get this to work but it involves a hack which apparently the main author here is not fond of. Well, you can either wait years for some magical reversing to happen for DC (probably never) or we can just implement a hack and call it a day. 

I implemented this in reicast libretro at least, it's up to upstream what they do honestly, I've long since stopped caring since apparently fixing bugs here is the last of the concerns of this project and setting up 'nonprofits' is far more important or some dumb bullshit.

**Comment by twinaphex** [comment]
I added a hack for this in libretro-reicast, it at least works there fine.

**Comment by sabula310** [comment]
cool

**Comment by sabula310** [comment]
how did you do it

**Comment by twinaphex** [comment]
By implementing a hack which both MrPsyMan and skmp seems to be against, so have fun waiting until 2020 (or 2030) before some magical reversing has happened to fix this.

Until then, you can just use libretro-reicast instead.

**Comment by LoungeKatt** [comment]
@twinaphex https://github.com/reicast/reicast-emulator/tree/lk/retrofit

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#49
