### ISSUE TITLE
Android 2.3.2 xperia play issue

### ISSUE THREAD

**Issue by psxpetey** [reicast/reicast-emulator#657]
Emulator runs fine or appears too. The paths seem to be correct but when I try to run the bios it vibrates but does not load also the config files do not get made upon booting bios. Ideas? Also after a few startups the emu crashes

**Comment by LoungeKatt** [comment]
reicast does not run on the Xperia Play unless you use the Ice Cream Sandwich beta or a third-party build that is ICS or higher.

https://github.com/reicast/reicast-emulator/issues/6

**Comment by psxpetey** [comment]
so gingerbread is not supported at all?

**Comment by LoungeKatt** [comment]
Not for that specific hardware.

**Comment by psxpetey** [comment]
thats a shame. Is there a gingerbread version of reicast at all? I understand that it may not work but I would like to give it a try and check the logcat to see why.

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/issues/239
https://github.com/reicast/reicast-emulator/issues/6

Gingerbread support stopped in late 2014 / early 2015

There should be more than enough information in the two issues above, since this is something that received a lot of attention until it was decided that it could not be resolved.
