### ISSUE TITLE
Add support for CHD v5 file format

### ISSUE THREAD

**Issue by sl1pkn07** [reicast/reicast-emulator#676]
Hi

reicast only support CHD v4 file format. but newer chman (>v146) make a CHD v5 format, that is not recognized by reicast

please add the support to CHD v5 file formats

greetings

**Comment by skmp** [comment]
This has long been in my wishlist, but chdv5 is a *PITA* to include. Tons of dependencies

**Comment by ManuelAMS** [comment]
While looking for info on the CHD format I found this recent discussion:

https://github.com/libretro/Genesis-Plus-GX/issues/93

There they mention a standalone library for chd v1-v5 support: https://github.com/rtissera/libchdr/

**Comment by crocket** [comment]
To simplify file management, I like to combine one GID file and several BIN files into one CHD file.
However, Gentoo's chdman supports CHDv5 only.

**Comment by ManuelAMS** [comment]
chdman stopped supporting CHDv4 writing as soon as CHDv5 was released. The last chdman version that allowed creating CHDv4 was 0.145. If you can't find it in your distro's repositories, you'll need to grab the MAME 0.145 source code to build it (since it's a tool made for MAME and released with it, and using its same version number). Ah, older chdman's parameters are slightly different from modern versions (<chdman -createcd file.gdi file.chd> instead of <chdman createcd -i file.gdi -o file.chd> IIRC).

Also keep in mind that CHDv4 was not loseless, so you can't recover the original GDI files from them (while that's possible with CHDv5) so I'd keep the untouched GDI too.

**Comment by skmp** [comment]
closing in favor of #18
