### ISSUE TITLE
Crowdfunding campaign

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#692]
I'm working this weekend on it. Care to give some feedback on https://docs.google.com/document/d/1YWImB01MAUx4XU4_LKm3iQEaTfr206ol1z1EJa09x90/edit?usp=sharing & join irc for discussion? I'll be doing the shooting tomorrow. Scenery: https://twitter.com/teh_skmp/status/619829831568621568.

Ding DING DING @MrPsyMan @LoungeKatt @hooby3dfx @Holzhaus

**Comment by LoungeKatt** [comment]
Going by just what the document says and nothing else, the message reads "If you donate to this project, you will provide me the means to quit my other jobs and dedicate that time to reicast"

I am not trying to sound rude, but it is hard to find the right words. It seems a little wrong to promise r7 for midway through a campaign for funding when it was already promised for midway through June. It sends the wrong message. You need to focus on how funding will impact the project, not how you need the funding and you promise you'll deliver XYZ. I get what you are trying to say, but at the same time you don't want to give the impression that everything the community has contributed until now didn't matter. You also don't want to deter future contributions by making it sound like a sweatshop.

**Comment by skmp** [comment]
Go on, don' t mind sounding rude. I don't get offended. The reason I posted this here is to get feedback. There has been a nice community building around the project and I don't want to disturb that. In fact, I want quite the opposite.

> "You need to focus on how funding will impact the project, not how you need the funding and you promise you'll deliver XYZ."

I don't need the funding. I have two stable contracts, one based in Netherlands and one here in Zurich. From a money perspective, I would be taking a financial hit. 

However, I indeed cannot any longer support reicast on my free time - my free time is filled with other stuff and it's been like that for a couple of years now. Non-computer stuff. And no-one has stepped up to do the major work required on all of the emulation internals, partly because the code is so effed up, partly because it's very specialized knowledge, and partly because no one cares enough. Same thing happened to nullDC and eventually the project died. 

I feel like both of these projects are my children. I've spent countless hours debating over assembly forms for the jit, falling asleep on printed SH4 docs on my desk, going to school with printouts from various emulators and hardware manuals to build up the knowledge required, singing to myself in sh4 opcodes, debugging on for weeks that Ikaruga invisible bullet bug w/ PIX (that's the funniest bug I've ever fixed), walking around the woods in Berlin sketching out the new, efficient register allocator for arm. I got to 160 kgs because I was so obsessed with it. I spent my 2008 birth~~day~~ week hacking up and releasing netplay support. You get the picture.

The reason "I need" this crowdfunding is so that I can have a clear answer, if it is viable to me to keep working on this, or if it is time to bid farewell and move on. Last time I had to make that decision was in [2010](http://ngemu.com/threads/nulldc-project-is-over-at-least-my-part-in-it.134968) and it was a very hard thing to do. But it was what I needed to do back then. The reason reicast isn't called nullDC is that I wanted a fresh start, and with ZeZu gone it didn't feel quite appropriate.

> "It seems a little wrong to promise r7 for midway through a campaign for funding when it was already promised for midway through June."

r7 is not promised, I just think it would make for great timing at that time. This doc won't be public or part of the campaign as is, it is more a map if my idea for the execution plan, and texts I'm working on to make it happen. The reason I posted it here is to get feedback and see what the rest of the devs feel. 

I'd rather not go at all for the "money-for-features" thingy, but people being what they are, and me having scanned 100+ campaigns the past months, I don't think it'll be successful that way. I'll be working on a draft for intro and main texts today.

The June release didn't happen because I had to take on a small contract to pay off some new taxes my mother couldn't afford (great way to spent "vacations"), and we're not quite stable enough to do the release without a proper implementation of #652 (most Android 5 phones are broken atm, going by the emails I receive). And the discussion for the logo/banners didn't get anywhere so I have to decide/solve this as well.

I always have a rule of never promising releases, which I keep breaking, and keep failing to deliver.


> "You need to focus on how funding will impact the project, not how you need the funding and you promise you'll deliver XYZ" (take two)

Alright, I'll work on this (focus on how funding will impact the project)

> "but at the same time you don't want to give the impression that everything the community has contributed until now didn't matter"

Of course I don't and of course it matters. Particularly without your work on the UI front we'd still most likely have the r5 ui. Thanks all these contributions I've managed to keep myself busy with more of the internals and a bit of PR and less with other things. I'm very grateful for that.


I'd love to hear some counter proposals, modified text/execution plan, or even  a "fuck you no crowdfunding". If there's no feedback I'll just do my best guess, which will of course be far worse.

~

**Comment by skmp** [comment]
Oh, and another point I missed.

> Going by just what the document says and nothing else, the message reads "If you donate to this project, you will provide me the means to quit my other jobs and dedicate that time to reicast"

The message from my side is

"If you want me to keep at this project, and actually be a project leader, this needs to replace part/all of my work time, because I no longer do coding on my free time. I believe there's a lot of things that I can help deliver if this happens. I'd also like to sponsor the time of other dedicated people to the project if they want to, because if they just work for free it feels abit like a sweatshop to me"

I do believe open source is a sweatshop making you contribute for free or face ideological failure, despite the fact that in reality [most of the open source development is sponsored](http://www.techrepublic.com/article/for-50-percent-of-developers-open-source-is-a-9-to-5-job) and companies profit off your work (in our case JXD, and others that embed reicast)

**Comment by skmp** [comment]
Also, I'll be more than happy to include more people in the video, if anyone wants to step up for this. *patiently awaits responses*

**Comment by LoungeKatt** [comment]
It's like I said, I get where you're coming from and I get how donations are seen as just as much a purchase of future progress. Most of my open source work has been in firmware and kernels, where donations were the only legal route to maintain a project. 

Instead of saying you have to choose if the project continues or it's time to let it die, you are trying to find a way not to let it fade ever again. It's all about presenting a "glass half full" version.

What I meant by not sounding like past contributions weren't enough or that it's a sweatshop is better explained by your response. Saying nobody stepped up, even if you justify why they couldn't after, sounds spiteful. I know I would have branched out into the core if I could follow it and I know you want to make it that I could. That's what I want to hear. "Having more time to work on the project means everything is a priority, such as cleaning up the code to help make contributing easier"

Reicast has a huge following BECAUSE you opened it up to the public. People don't contribute because they think you failed, they contribute because they want you to succeed. Nobody needs you to ask them to help, they just need to know how they can.

**Comment by skmp** [comment]
Working to integrate the feedback. From a storytelling perspective, which video structure do you prefer? So far #2 has far more votes.

In retrospect, the current ideas are a bit too much me-centric. I'll work on that part as well.

**Comment by LoungeKatt** [comment]
Agreed. Number 2 sounds far less like a monologue and has more of that "we can do this together" feel. 1 sounds like the textbook corporate sponsorship presentation. You could always edit what you put together with 2 to follow the structure of 1 in the future, though.

**Comment by Holzhaus** [comment]
> my free time is filled with other stuff and it's been like that for a couple of years now. Non-computer stuff. And no-one has stepped up to do the major work required on the emulation internals, partly because the code is so effed up, partly because it's very specialized knowledge, and partly because no one cares enough.

I have very little knowledge about actual emulation work (as you may have noticed, my contributions solely consisted of code cleanup and stuff like that), so I may be on the wrong path here, but I think that crowdfunding campaigns are unsuitable to secure a steady income. Maybe enough people will donate enough money to keep your head above the warter for a month or two (or even more), but after that period reicast will face the same problem it is facing now.

That a problem and I don't know how to fix that other than getting a company to sponsor you (dunno how realistic that is) or to sanitize the codebase to reduce the barrier for other people to get involved in development, so that the dev work doesn't have to fall on you alone.

To archieve the latter, the focus should be on code cleanups (abstraction & reusability, simplicity and reducing/centralising platform-specific stuff) and documentation (code commenting, explaining how the emulation works) rather than on shiny new features. I know that this might be unpopular among end-users, since they won't notice much, but that will help other developers to start contributing in the long run. 

There need to be new features of course (otherwise people won't spend any money I assume), but they shouldn't be too ambitious, because cleanup and documentation should be priority.

Just my two cents.

**Comment by robertybob** [comment]
I'd personally like to see this campaign being feature-based e.g 15k gets 4 months of bug fixes and 3 months of work on: dedicated Windows / RasPi releases. Then stretch goals being something like: 5k extra gets 1 month more time spent on feature X etc.

I don't think spending thousands of $ on making the code more accessible is worthwhile - better features will get more people interested and will hopefully get more devs involved. If enough people were interested in helping at the moment I'm sure they'd make more of an effort to do so.

**Comment by LoungeKatt** [comment]
@Holzhaus how I saw it was not that it was meant to be a permanent solution, just a way to buy enough time to get the project at a point where it didn't need as much attention or @skmp directly to resolve issues.

**Comment by robertybob** [comment]
@Loungekat I was just thinking that it would be easier to get attention and make more of an impact if , when selling the funding campaign, that the aim was to bring missing features X, X and X ..rather than code cleanup. ..depends who you're aiming the funding campaign at I suppose, I'm one of those people who has no knowledge or interest in coding.

**Comment by LoungeKatt** [comment]
@robertybob So let's assume it's literally $ / feature. 

(Hypothetical) skmp promises you support for a dreamcast keyboard at $100. The games that use it still have graphics issues, there are still crashes, etc. The rest of us can't really resolve those issue because we need skmp and us doing the keyboard so he can work on the core just invalidated the entire $ / feature promise. You get keyboard support, but the game you wanted it for keeps crashing.

As @skmp said, the biggest reason for this campaign is that there is nobody else to work on the core and this is a way to solve that. Would it be good enough to say what things would be fixed? There is always the possibility to decide what new features that would allow and then say it would allow for missing feature X. That way you would still get a feature, we don't lie to you, and reicast gets what it needs.

**Comment by robertybob** [comment]
@LoungeKatt I take your points on-board. I suppose what I'm getting at is for $x, or for x months work, I'd preferably like to see some obvious benefit at the end (like a brand new feature or cross-platform compatibility). However, if it's explained how me donating $20 will eventually get me a Windows version to play on and stability in my favourite games, then that'll more than suffice. 

Forgive my ignorance, but would it hypotheticallyviable to say 'we're going to work on improving the stability of these 25 popular games' and focus on those, rather than changes which may only benefit obscure games that 90% of Reicast users won't ever play ?

**Comment by LoungeKatt** [comment]
It should be possible to link what's being fixed to the game or games it would fix. If not specific titles, at least a description. An example would be "games with mini maps that aren't showing"

**Comment by hooby3dfx** [comment]
@skmp, i think this statement from earlier in the chain nails your point
perfectly and could be used in your story/video pretty much as-is:

"I don't need the funding. I have two stable contracts, one based in
Netherlands and one here in Zurich. From a money perspective, I would be
taking a financial hit.

However, I indeed cannot any longer support reicast on my free time - my
free time is filled with other stuff and it's been like that for a couple
of years now. Non-computer stuff. And no-one has stepped up to do the major
work required on all of the emulation internals, partly because the code is
so effed up, partly because it's very specialized knowledge, and partly
because no one cares enough. Same thing happened to nullDC and eventually
the project died.

I feel like both of these projects are my children. I've spent countless
hours debating over assembly forms for the jit, falling asleep on printed
SH4 docs on my desk, going to school with printouts from various emulators
and hardware manuals to build up the knowledge required, singing to myself
in sh4 opcodes, debugging on for weeks that Ikaruga invisible bullet bug w/
PIX (that's the funniest bug I've ever fixed), walking around the woods in
Berlin sketching out the new, efficient register allocator for arm. I got
to 160 kgs because I was so obsessed with it. I spent my 2008 birthday week
hacking up and releasing netplay support. You get the picture.

The reason "I need" this crowdfunding is so that I can have a clear answer,
if it is viable to me to keep working on this, or if it is time to bid
farewell and move on. Last time I had to make that decision was in 2010
<http://ngemu.com/threads/nulldc-project-is-over-at-least-my-part-in-it.134968>
and
it was a very hard thing to do. But it was what I needed to do back then.
The reason reicast isn't called nullDC is that I wanted a fresh start"

**Comment by skmp** [comment]
@robertybob Prioritizing a few games at expense of others is always inviting for huge problems in a project like this. If anything, you want to go the other way. There's no better way to squash bugs and ensure a great implementation that to test many different ones. I've tried to keep a pragmatic approach to this on nullDC (and not really on reicast) and I think that's one of the reasons the emulator was so much loved. It had it's own fair of bugs, and things that it didn't do, but on what it did it worked reliably, without (many) unexpected issues midway a game. 

@hooby3dfx That part makes for a nice story, but as @LoungeKatt very well put it is extremely focused on -my- story and -my- issues. After thinking over it I think I'd like to put it more from the team perspective. The "team" facade that was kept over nullDC has left me a bit bitter (people thinking it's an actual "team" and not realizing we're not their private army of happy-to-indulge them coders). This isn't about me getting funding, or even the project surviving. It's about Dreamcast emulation getting better. It's a fine line to walk I guess.


@LoungeKatt, @Holzhaus This is going to be an experiment right now. However, I don't quite see why it can work, over and over, for often underwhelming products that come many months delayed to the market and not work for open source dev. We already have a "product", can do quick releases, and can run a much more open/transparent operation. It works for Wikipedia, too. I think the trick to this is to target people that can afford to and are used to paying (consumers) rather than devs. Devs rarely have funds to spare or feel like paying. But they contribute, so I guess it's a fair game. In any case, even if this only happens once I want to leave the project in a much, much, much better shape.

@LoungeKatt, @Holzhaus, @robertybob Usually new features are implemented via cleanups, that keeps the code sane. I've violated the normal implement-refactor-improve-iterate-repeat cycle many many times in reicast, so there's quite a bit of technical dept. Nothing insuperable though. To cleanups, there it plays a huge factor that I know all of the code-base (except the java parts) and have already experimented with 4-5 project and file structures. I'm thinking to go half-half on this. 

@robertybob Users have no clear understanding of their wants. They want you to delight them with something, then explain to them why it's so good and relevant to them. You not only have to do your  work, but also do their part since people are lazy. Users do know when it's done right, though. You build a successful product by following your user's needs/emotions, rather than their claims, and keep persuading them to do the right decision for themselves. (Omg all these years in startups are starting to paying off)

I decided to delay the video to the next weekend, I want to do a 3rd revision of my thoughts

**Comment by LoungeKatt** [comment]
@skmp It sounds like everything I was trying to say was taken exactly as intended. As far as I am concerned, we are on the same page and I have no concerns about backing the campaign.

**Comment by Holzhaus** [comment]
@skmp @LoungeKatt ACK.

**Comment by hooby3dfx** [comment]
a couple random thoughts:
-announcement related to PC port could get good PR. dolphin got a ton of
hits and a couple articles on pcgamer site when they had some big
performance improvements.
-could other non-DC emulators/devs give a shoutout? (i.e. dolphin)
-was steam greenlight ever evaluated?

**Comment by hooby3dfx** [comment]
example of emulator project status update done really well:
https://dolphin-emu.org/blog/2015/08/01/dolphin-progress-report-july-2015/
something like that may help engage audience/get attention

**Comment by LoungeKatt** [comment]
@hooby3dfx It almost makes you forget that it includes dropping support for nearly every device with how well they make even the smallest changes sound like groundbreaking advances in technology.

**Comment by skmp** [comment]
(See the update in #1148 wrt bountysource)

**Comment by LoungeKatt** [comment]
[![Two Dollars](http://img.youtube.com/vi/FsxJfcFVnpo/0.jpg)](http://www.youtube.com/watch?v=FsxJfcFVnpo)

**Comment by skmp** [comment]
Closing this. Will open a new one if we do a specific fund raiser
