### ISSUE TITLE
Unified makefiles

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#715]
This is to track the amazing progress done by @Holzhaus on the Linux Makefiles, #703 #705 #708 (and  possibly more)

Feedback so far
- I really like it!
- I think it makes sense to store the objs on obj($ARCH)... so that we don't have to clean between different arches
- I'd love x86 to alias i686 and x64 to alias AMD64 (saves typing, yes i'm that lazy)
- Possibly merging LinCPP (We may need a new TARGET there, to use CPU_GENERIC)
- Improve cross compiler support
- replace ../../ w/ **/**/ instead of hard-replacing the relative path for the obj generation (android & nacl do it this way)

These sound sane as ideas?

_edit_
We also need to srsly re-think the entire TARGET_*, HOST_* and FEAT_* thingy so that it makes sense... now it doesn't quite and responsibility is spread all over C macro logic and makefile logic, which sucks

**Comment by Holzhaus** [comment]
> I really like it!

Thanks!

> I think it makes sense to store the objs on obj($ARCH)... so that we don't have to clean between different arches

Done.

> I'd love x86 to alias i686 and x64 to alias AMD64 (saves typing, yes i'm that lazy)

Done.

> Improve cross compiler support

Good idea. Compiling with different compilers is a very easy way to spot additional bugs and fuzzy code. Check #718 and #719.

> Possibly merging LinCPP (We may need a new TARGET there, to use CPU_GENERIC)

Done. However, it doesn't seem to work with `-fsingle-precision-constant`, so I needed to add it to every single platform except lincpp.

By the way: Does lincpp work on every CPU? If so, we could make it default to lincpp if no supported platform has been detected (instead of exiting with an error).

> replace ../../ w/ // instead of hard-replacing the relative path for the obj generation (android & nacl do it this way)

Can you elaborate? I'm not sure what you want me to do ;-)

**Comment by skmp** [comment]
rec-cpp is much slower compared to a normal jit, I think it's best to never use it by default. If the user really wants to do an experimental build, they can always force it. (This is a way to make sure users read the readme or other build instructions).

`-fsingle-precision-constant` isn't compatible w/ c++11. I don't think it really brings much of a measurable speed benefit, but let's keep it for now like that. I have to crawl though the source and see any double precision constants that might need to be removed.

**Comment by LoungeKatt** [comment]
> We also need to srsly re-think the entire TARGET_*, HOST_* and FEAT_* thingy so that it makes sense... now it doesn't quite and responsibility is spread all over C macro logic and makefile logic, which sucks

TargetConditionals.h is a part of the default headers for Mac / iOS so TARGET_ is available without any local definitions on 1/3 of the platforms.
ARCH_ would be a bit more common than HOST_, even though HOST_ is self-explanatory.
FEAT_ would be CONFIG_ in kernels and such, so that could be an easy transition and a little easier to follow, especially when first looking through.

**Comment by skmp** [comment]
(closing this)
