### ISSUE TITLE
Pushing r7, take two

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#746]
APK http://reicast-builds.s3.amazonaws.com/builds/heads/master-71c2cb4/reicast-android-debug-71c2cb4.apk (latest master)

https://www.facebook.com/reicastdc?fref=nf take a look on the feedback. Lots of people "Crashes after Dreamcast boot screen". Some report it works on problematic phones now. It works perfectly on all the available hardware I have.

I wonder if anyone can replicate that?

Apart from that, it seems to be mostly working as expected.

**Comment by skmp** [comment]
(spamming @MrPsyMan @LoungeKatt @Holzhaus @lioncash @hooby3dfx)

**Comment by Holzhaus** [comment]
Just tested it on my Samsung Galaxy Note 10.1 2014 Edition. Both Incoming and wagtk work fine. 

*Nitpick: The Android UI is rather ugly on my device, since the fonts are non-standard and much too large.*

**Comment by LoungeKatt** [comment]
@Holzhaus non-standard? Like the use of bold for headings or something you did to your device?

**Comment by Holzhaus** [comment]
@LoungeKatt No sure. Might be just the size.

**reicast:**
![reicast](http://i.imgur.com/mlEMTEW.png)

**VLC (Material Design):**
![VLC (Material Design)](http://i.imgur.com/JhilPgK.png)

**Comment by LoungeKatt** [comment]
Gotcha. The menus are intentionally set to either medium or large text. It was meant more for phones but, if anything, it shouldn't open the drawer all the way on a tablet so it looks the same.

**Comment by LoungeKatt** [comment]
Sadly, the library doesn't base it on the width of the drawer, but instead uses the width of the remaining view. The width of the drawer would be screen size minus the drawer offset.

It's not something I could complete in the next five minutes, but I did add a separate offset for large screens that will make the menu smaller thinner for now. Ideally, this will be calculated at runtime (or possibly switched to a new library as better ones exist now).

https://github.com/reicast/reicast-emulator/commit/52b423f42b21b66689b7d5d502f066578b4dc67f

**Comment by Holzhaus** [comment]
@LoungeKatt I understand the intention, but to be true: I never had problem with font size on my phones or tablet with the standard theme (Material Design or Holo). Even on my Phone, reicast's fonts are too large.

Why not just use Material Design instead of something custom?

**Comment by LoungeKatt** [comment]
@Holzhaus It was never about you specifically having an issue with the font size on your phone. It seems like you are telling me that because the font size in reicast's menu is not the same as the one in VLC, it is ugly. VLC doesn't play Dreamcast games, either, so it might not be so bad they are different.

When I said "(or possibly switched to a new library as better ones exist now)" that was referring to how the menu is over a year old. Besides, material design is what EVERY app is using. Dolphin switched to it because their original UI was not far off. Seriously, though, it's been the same UI for over a year. You really waited until now to say something?

**Comment by LoungeKatt** [comment]
Advantage: uses standard android library instead of extension

Disadvantage: considerably larger code footprint, loss of the slide away effect (see below)

![screenshot_2015-08-13-14-30-19](https://cloud.githubusercontent.com/assets/1173913/9258190/0d7af1b8-41c8-11e5-8cdf-589500796837.png)

**Comment by Holzhaus** [comment]
Hmm, what about [SlidingPaneLayout](https://developer.android.com/reference/android/support/v4/widget/SlidingPaneLayout.html)? VLC uses a [modified version](http://git.videolan.org/?p=vlc-ports/android.git;a=blob;f=vlc-android/src/com/android/widget/SlidingPaneLayout.java;h=19e8084289c2457ffaf1d9747fa949f46b727c9b;hb=HEAD).

**Comment by LoungeKatt** [comment]
It is a contradiction to request not using a custom library, then refer to a custom library that some other application has modified.

There is the color scheme, which is independent of method
There is the font style, which is independent of method
There is the drawer animation, which depends on the library

Which of these is it you are trying to change? Because SlidingDrawer == DrawerLayout == SlidingPaneLayout in terms of functionality. 
Material Design's NavBar is just a wrapper around DrawerLayout.

**Comment by Holzhaus** [comment]
I'm not saying that we shouldn't use a custom library. Actually I didn't even look at the code of the android app. I was only concerned about the visual style (i.e. that the fonts are too large and the drawer almost takes the whole screen on my tablet). In my opinon, that's an issue.

About "standard theme" vs. "custom": I just wanted to say that I like how the VLC app looks - which is entirely personal preference - and I asked why reicast doesn't use that style. If you like the current style better, that's fine. I'm not saying that we need to change it (except for the drawer issue).

**Comment by LoungeKatt** [comment]
I can make the fonts smaller if it's a shared opinion. It is independent of the API altogether.

VLC is a cutting edge media player, reicast is an emulator for a system from the 90s. Dolphin used Material because that was the Nintendo look. Play! used it because their UI developer wanted to support color-based themes. I never saw a reason for reicast other than to "assimilate"

**Comment by LoungeKatt** [comment]
I'm not sure why the font sizes ended up specifically defined, but it's possible turning the exact point back over to the system will make it scale better on your device. It would probably be best to test that out before anything is actually changed to another size.

**Comment by mk8itra1n** [comment]
Any updates about the r7 iOS version of reicast. Any pictures, videos of it or anything?

**Comment by skmp** [comment]
Alright. No one seems to have managed to replicate the crash reports issues so far. Let's hope this doesn't explode on our face to much...

**Comment by skmp** [comment]
*testing comment*

**Comment by skmp** [comment]
(R7 was released a long time ago)
