### ISSUE TITLE
Naomi support for linux makefile

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#795]
@Holzhaus maybe you can take a for this? it needs to -D TARGET_NAOMI and change binary to reicast_naomi.elf

Also, I'm not sure how much sense the .elf extension makes for the Linux crowd. It makes a ton of sense for me, but I've used .elfs a ton for dc/ps2/wii development and I thin the typical thing in linux is to not keep the extension. Could we also do a make install ?

**Comment by Holzhaus** [comment]
I need some more info:
Can naomi support be included alongside normal reicast?

So could I just do:
```
ifdef SUPPORT_NAOMI
    CFLAGS += -D TARGET_NAOMI
endif
```
So that you can do `make SUPPORT_NAOMI=1` to get Naomi support?

Best thing would be to enable Naomi support by default and add a config entry to enable/disable it at runtime.

Also, why do we need to change the executable name?

Anyhow, I'm already working on a `make install` Makefile target.

**Comment by skmp** [comment]
No, the naomi build only supports naomi. The plan is to have all hosts at a single binary eventually, but the current setup allows us to get a few %s faster speed. I haven't measured the cost, which I should do (among other things...) but it's how it is atm. 

We could by default build two targets, reicast and reicast-naomi (though, this would double the time do a build)
