### ISSUE TITLE
Split screen game rendering completely broken

### ISSUE THREAD

**Issue by Holzhaus** [reicast/reicast-emulator#824]
**Platform:** Linux x86_64 (X11/GLX)

Split screen rendering seems to be broken (with X11/GLX at least). The two screens seem to be "combined" somehow. Single player works fine though (and also games like Soul Calibur that don't use splitscreen).

Here's an example screenshot from the game [Incoming](http://www.mobygames.com/game/dreamcast/incoming-the-final-conflict).

![Incoming split screen](http://i.imgur.com/BVRdL3A.png)

Here's how it _should_ look (Screenshot taken from [mobygames.com](http://www.mobygames.com/game/dreamcast/incoming-the-final-conflict/screenshots/gameShotId,17424/)):
![Incoming split screen (proper)](http://www.mobygames.com/images/shots/l/17424-incoming-the-final-conflict-dreamcast-screenshot-split-screen.jpg)

Ignore the color difference, the former is the "Africa Level", the latter is the "Antarctica" level.

**Comment by skmp** [comment]
That's because clipping isn't implemented, and that's because clipping is
extremelly slow on some mobile hardware that I had to turn it off

On Sat, Aug 29, 2015 at 12:51 AM, Jan Holthuis <notifications@github.com>
wrote:

> *Platform:* Linux x86_64 (X11/GLX)
>
> Split screen rendering seems to be broken (with X11/GLX at least). The two
> screens seem to be "combined" somehow. Single player works fine though (and
> also games like Soul Calibur that don't use splitscreen).
>
> Here's an example screenshot from the game Incoming
> <http://www.mobygames.com/game/dreamcast/incoming-the-final-conflict>.
>
> [image: Incoming split screen]
> <https://camo.githubusercontent.com/6f33db0b43a26dd403d11f43e5d8f557b523527a/687474703a2f2f692e696d6775722e636f6d2f425652644c33412e706e67>
>
> Here's how it *should* look (Screenshot taken from mobygames.com
> <http://www.mobygames.com/game/dreamcast/incoming-the-final-conflict/screenshots/gameShotId,17424/>
> ):
> [image: Incoming split screen (proper)]
> <https://camo.githubusercontent.com/8f2be1398d950ab8245a82bd11f21b74e80c06b4/687474703a2f2f7777772e6d6f627967616d65732e636f6d2f696d616765732f73686f74732f6c2f31373432342d696e636f6d696e672d7468652d66696e616c2d636f6e666c6963742d647265616d636173742d73637265656e73686f742d73706c69742d73637265656e2e6a7067>
>
> Ignore the color difference, the former is the "Africa Level", the latter
> is the "Antarctica" level.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/824>.
>



-- 
~skmp

**Comment by Holzhaus** [comment]
Does that code still exist? Can if `#ifdef` it for the moment?

**Comment by skmp** [comment]
Nope, looks like I have to add it again on the shaders

On Sat, Aug 29, 2015 at 6:37 PM, Jan Holthuis <notifications@github.com>
wrote:

> Does that code still exist? Can if #ifdef it for the moment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/824#issuecomment-136007903>
> .
>



-- 
~skmp

**Comment by twinaphex** [comment]
@skmp Have a GLES2 codepath and a newer GL codepath then, or do you prefer inconveniencing users for years by just not wanting to implement clipping? Because nullDC implemented it just fine with the D3D9 renderer. Now, you can tell me a lot of bullshit, but surely inbetween GL 3.x and GL 4.3, you can work something out to get this properly implemented, and it surely shouldn't take 'years' either. There is nothing with this feature that requires a major funneling of money, you could do this in 15 minutes if you really cared. Fast forward a year ago and you still didn't bother implementing this.

This is quite some bullshit honestly. How many months and years until you're going to get off your ass and finally start implementing this whenever this non-profit arrives out of thin air dude? How much longer are you going to waste people's time with this bullshit? Why should people support your new efforts when you waste their time for years with this kind of crap?

**Comment by twinaphex** [comment]
Oh wait, forgot, this shady company in Hong Kong or whatever the hell 'owns' the GL code now, that's why you can't edit it, forgot, riiiiiiight. And that's why we need a 'license switch' so we can change it from GPL to MIT because of... because of what really?

See, it's all these 'which comes first - chicken or the egg?' scenarios that makes it really tiresome to do anything on a collaborative level with this project, and it all comes back honestly to this kind of non-caring attitude from the author.

**Comment by robertybob** [comment]
@twinaphex At least the Saturn is getting some love and attention :+1:

**Comment by twinaphex** [comment]
Yeah, and he just removed me from his organization because you can only kiss this little Greeks ass, but a bit of long overdue criticism? Nah, we cant have that.

Have fun pushing code and commits in Stefanos sweatshop. Apparently the things we contributed to him before (multiple code commits fixing ACTUAL game compatibility bugs, not just silly frontend stuff of no significance), that all doesnt matter as soon as you rub his little ego the wrong way, you get discarded like dog shit.

**Comment by twinaphex** [comment]
Hmm, I got removed and unremoved again so I dunno what is going on.

Ill assume there was a change of heart then.

**Comment by skmp** [comment]
This should be solved by #1151. Please re-open if not
