### ISSUE TITLE
Add some user interface to Windows build [$130]

### ISSUE THREAD

**Issue by ofry** [reicast/reicast-emulator#831]
For sample, Open file, Open BIOS, Select BIOS, Save/load state, etc.

**Comment by Holzhaus** [comment]
We should probably separate the Desktop GUI from the emulator code and use an approach similar to what mupen64plus does: http://m64py.sourceforge.net/

That way we'd have a unified code path for all platforms and don't introduce big dependencies in case we don't need a GUI.

**Comment by ofry** [comment]
Yes, it's possible too ^^

**Comment by ofry** [comment]
#630 I think it's related. Because if we port it to libretro, it can be good GUI for this emulator :+1:

**Comment by skmp** [comment]
I'm always in more "integrated" things than just a front end (So that you can actually pause and change settings during run time). Most of the user friendly things can't be done yet though (save states don't exist, input is only keyboard for windows)

**Comment by Holzhaus** [comment]
That doesn't conflict with the python-gui approach. You can actually call c functions from python and vicd versa. I was already looking into doing something like that, but stumbled over a bug in my SDL2. I see if I can work around that.

**Comment by skmp** [comment]
Well, that could work then. (Keep in mind python is a very foreign and pita to setup thing for windows users, though)

**Comment by Holzhaus** [comment]
Well, there are things like [pyexe](http://www.py2exe.org/) which turn python programs into exe files that are runnable without python installed. The m64py people even have a Windows portable build for download, so has to be a way to make it user friendly. I'll look at the code and get in touch with them eventually.

We should think about separating the current platform-specific user-interface stuff (loading settings, creating a render surface, and sorts) from the core reicast code, so that we can turn the latter into a shared library that both the current UI and the future GUI can access.
That way, a user can simply install reicast and if he/she later decides that a GUI is required, it can be installed afterwards, but you don't have to compile and keep a second copy of the core reicast stuff. This mainly affects linux - windows users usually expect a GUI (and the display server is installed anyway), so if we had a GUI, I think we should always include it in the windows version.

**Comment by Holzhaus** [comment]
I've got a basic Python GUI working now, which does not integrate with reicast just yet, but the concept seems to work. After the GUI is created, I get the HWND/XWindowID of one of the widgets and pass it to some C code that creates an SDL2 window with OpenGL 3.1 support from it and draws a black background on it. Works fine as far as i can see.

That GUI is currently written in Tkinter (Tk/Tcl), since that is part of the python standard library. wxPython might be prettier and look much more native, but that can be done later. 

I'm currently working on the reicast infrastructure part. As I said, I'd like to make reicast a shared library that my glue code can dlopen and call stuff like `dc_init()`, `dc_run()` etc from there.

I'll use #832 as a base for that, since I need SDL2 (SDL1 does not have support for the OpenGL 3.1 core profile).

**Comment by Holzhaus** [comment]
It works!

Code isn't quite ready for merging yet, but it does work.

![Working Reicast GUI](http://i.imgur.com/CHKNIt3.png)

**Comment by Zetchzie** [comment]
Id really like this im not knowledgeable enough to configure everything lol just need to be able to set up my xbox one controler.

**Comment by Zetchzie** [comment]
Id really like this im not knowledgeable enough to configure everything without a gui lol

**Comment by Zetchzie** [comment]
Id really like this im not knowledgeable enough to configure everything without a gui lol

**Comment by skmp** [comment]
@Holzhaus any progress on this? Would be nice to have an MR no matter the state, so people can improve it

**Comment by skmp** [comment]
I guess https://github.com/reicast/reicast-emulator/compare/holzhaus/gui ? Will review later on. Also #1150 for follow up

**Comment by Mored1984** [comment]
I hope to solve the issue with no bug for Windows 10 (x64)

**Comment by baka0815** [comment]
I would also keep the GUI separated from the core like @Holzhaus mentioned.
However I'm not sure if using Python would be a good idea as the rest of the code is C(++).

**Comment by baka0815** [comment]
What toolkit should be used for the GUI? I'm currently experimenting with Qt which would be available to Linux and Windows (not sure about Mac).

**Comment by AbandonedCart** [comment]
http://doc.qt.io/qt-5/supported-platforms.html?hsLang=en

@dmiller423 mentioned already starting to work on a Qt interface, too.

**Comment by skmp** [comment]
@flyinghead I think you should claim this now that the imgui UI has been added

**Comment by flyinghead** [comment]
Done. Just need this issue to be closed.
