### ISSUE TITLE
Check for OpenMP before compiling software renderer on Linux

### ISSUE THREAD

**Issue by FlyingJester** [reicast/reicast-emulator#885]
Some Linux systems (notable Musl setups) do not have OpenMP, and so cannot compile the software renderer.

It would be nice if there was a check for the OpenMP header (omp.h) before trying to build (and then failing to build) the software renderer.

**Comment by skmp** [comment]
OpenMP is required at this point for softrend, and softrend is rather experimental and not much useful overall, anyway. We don't have an autoconf script that checks these kinds of things -- we have instead opted for a simpler, human readable makefile. Since you're running a rather obscure configuration of linux I'll assume you know how to modify the linux Makefile to disable softrend. I'm a bit torn on supporting non-omp builds and such as this is a slippery slope of complicated builds. @Holzhaus what's your view?

**Comment by FlyingJester** [comment]
Maybe just add a variable to the makefiles to disable it? So that you could just run `make NOSOFTREND` or `make SOFTREND=NO`?

My make-fu is not really what it should be, so I'm not exactly sure how easy or hard that would be.

**Comment by Holzhaus** [comment]
Just use `make platform=x86` and softrend wont be built (no sse4.1)

**Comment by Holzhaus** [comment]
Sorry, hit the close button by accident

**Comment by skmp** [comment]
(Please re-open if still an issue)
