### ISSUE TITLE
all my games don't want to load on galaxy note 4 sm-n910f, help me please

### ISSUE THREAD

**Issue by haderach7777** [reicast/reicast-emulator#941]
Hello everyone! I tried lot of games, and all my games won't boot whith the last version of reicast(73e2691), my phone is the galaxy note 4 sm-n910f. Can you help me?? It is a problem with the options?

**Comment by BiYao** [comment]
You still wait! The need for better development of this simulator, I am not a developer, I am just a concern

**Comment by TheBurgerGuy** [comment]
Update to Android marshmallow dude and this will run flawlessly

**Comment by TheBurgerGuy** [comment]
How to say miss you but I tried it on Android marshmallow and it was great

**Comment by TheBurgerGuy** [comment]
You have to update manually through Samsung Kies or keys or something like thats

**Comment by haderach7777** [comment]
Thak you Biyao and the burgerguy.

BURGERGUY, you possess a european galaxy note 4 too?

**Comment by TheBurgerGuy** [comment]
Same thing I was researching on Samsung updates and you have to do a manual Update it's ready but t mobile and other carriers Won't let you download through phone it has to be through Samsung kies on the computer And you have the update Android Marshmallow 6.0 The emulator Runs Flawlessly. I had a problem with sonic adventure 2 Running way too fast now it got fixed with the update

**Comment by haderach7777** [comment]
Thank you

**Comment by skmp** [comment]
Closing, for General support please use http://forum.reicast.com
