### ISSUE TITLE
Problem with SD Card

### ISSUE THREAD

**Issue by Newerawe** [reicast/reicast-emulator#987]
If you use BIOS folder from your SD Card settings doesn't save and on screen buttons are invisible.
Android 6.0
Not such a problem, but it was difficult to found out cause of problem

**Comment by vlad54rus** [comment]
Android restricts write access to sdcard (starting with android 4.4), Reicast cannot do anything with it. You can overcome this issue, but you need root. Google SdFix.

**Comment by LoungeKatt** [comment]
I've added some fixes for "modern" Android devices, since the code to load content from the sdcard was written while Android was still playing with storage and releasing experimental builds.
Until it is approved / merged, you can download the APK with these changes from http://builds.reicast.com/ under the lk/cleanup header.
